/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAaveV3PoolDataProvider,
  IAaveV3PoolDataProviderInterface,
} from "../../../../contracts/interfaces/IAaveV3Pool.sol/IAaveV3PoolDataProvider";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getReserveData",
    outputs: [
      {
        internalType: "uint256",
        name: "availableLiquidity",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalStableDebt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalVariableDebt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "liquidityRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "variableBorrowRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "stableBorrowRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "averageStableBorrowRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "liquidityIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "variableBorrowIndex",
        type: "uint256",
      },
      {
        internalType: "uint40",
        name: "lastUpdateTimestamp",
        type: "uint40",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAaveV3PoolDataProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveV3PoolDataProviderInterface {
    return new Interface(_abi) as IAaveV3PoolDataProviderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAaveV3PoolDataProvider {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAaveV3PoolDataProvider;
  }
}
