/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IFeeDistributorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimFees"
      | "distributeFees"
      | "getPendingFees"
      | "grantReferralRole"
      | "grantVaultRole"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "claimFees", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "distributeFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantReferralRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantVaultRole",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "claimFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantReferralRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantVaultRole",
    data: BytesLike
  ): Result;
}

export interface IFeeDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): IFeeDistributor;
  waitForDeployment(): Promise<this>;

  interface: IFeeDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimFees: TypedContractMethod<[], [bigint], "nonpayable">;

  distributeFees: TypedContractMethod<
    [amount: BigNumberish, feeType: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPendingFees: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  grantReferralRole: TypedContractMethod<
    [referral: AddressLike],
    [void],
    "nonpayable"
  >;

  grantVaultRole: TypedContractMethod<
    [vault: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimFees"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeFees"
  ): TypedContractMethod<
    [amount: BigNumberish, feeType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPendingFees"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantReferralRole"
  ): TypedContractMethod<[referral: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantVaultRole"
  ): TypedContractMethod<[vault: AddressLike], [void], "nonpayable">;

  filters: {};
}
