/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AaveLoopStrategyV3 {
  export type RiskParamsStruct = {
    targetHealthFactor: BigNumberish;
    minHealthFactor: BigNumberish;
    maxLeverage: BigNumberish;
    maxLoopIterations: BigNumberish;
  };

  export type RiskParamsStructOutput = [
    targetHealthFactor: bigint,
    minHealthFactor: bigint,
    maxLeverage: bigint,
    maxLoopIterations: bigint
  ] & {
    targetHealthFactor: bigint;
    minHealthFactor: bigint;
    maxLeverage: bigint;
    maxLoopIterations: bigint;
  };
}

export interface AaveLoopStrategyV3Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "LEVERAGE_PRECISION"
      | "aToken"
      | "aavePool"
      | "balanceOfPool"
      | "borrowAsset"
      | "currentLeverage"
      | "dataProvider"
      | "deposit"
      | "emergencyWithdraw"
      | "estimatedAPY"
      | "estimatedTotalAssets"
      | "getAavePosition"
      | "getCurrentLeverage"
      | "harvest"
      | "healthFactor"
      | "isActive"
      | "lastReportTime"
      | "name"
      | "owner"
      | "pause"
      | "paused"
      | "rebalance"
      | "renounceOwnership"
      | "riskParams"
      | "setController"
      | "setRiskParams"
      | "setRiskParamsDirect"
      | "setVault"
      | "strategyController"
      | "sweep"
      | "totalAssets"
      | "totalDebt"
      | "transferOwnership"
      | "unpause"
      | "vault"
      | "want"
      | "wantToken"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "Harvested"
      | "LeverageDecreased"
      | "LeverageIncreased"
      | "LoopExecuted"
      | "OwnershipTransferred"
      | "Paused"
      | "RiskParamsUpdated"
      | "Unpaused"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LEVERAGE_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "aToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "aavePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOfPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrowAsset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentLeverage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dataProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "estimatedAPY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "estimatedTotalAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAavePosition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentLeverage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "harvest", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "healthFactor",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isActive", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastReportTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "rebalance", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "riskParams",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setController",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRiskParams",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRiskParamsDirect",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "strategyController",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sweep", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "totalAssets",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "totalDebt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;
  encodeFunctionData(functionFragment: "want", values?: undefined): string;
  encodeFunctionData(functionFragment: "wantToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "LEVERAGE_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "aavePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentLeverage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dataProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimatedAPY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimatedTotalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAavePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentLeverage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "harvest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "healthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastReportTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rebalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "riskParams", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRiskParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRiskParamsDirect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "strategyController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sweep", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalDebt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "want", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wantToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [caller: AddressLike, amount: BigNumberish];
  export type OutputTuple = [caller: string, amount: bigint];
  export interface OutputObject {
    caller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HarvestedEvent {
  export type InputTuple = [profit: BigNumberish, loss: BigNumberish];
  export type OutputTuple = [profit: bigint, loss: bigint];
  export interface OutputObject {
    profit: bigint;
    loss: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeverageDecreasedEvent {
  export type InputTuple = [newLeverage: BigNumberish];
  export type OutputTuple = [newLeverage: bigint];
  export interface OutputObject {
    newLeverage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeverageIncreasedEvent {
  export type InputTuple = [
    newLeverage: BigNumberish,
    iterations: BigNumberish
  ];
  export type OutputTuple = [newLeverage: bigint, iterations: bigint];
  export interface OutputObject {
    newLeverage: bigint;
    iterations: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoopExecutedEvent {
  export type InputTuple = [
    collateral: BigNumberish,
    debt: BigNumberish,
    hf: BigNumberish
  ];
  export type OutputTuple = [collateral: bigint, debt: bigint, hf: bigint];
  export interface OutputObject {
    collateral: bigint;
    debt: bigint;
    hf: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskParamsUpdatedEvent {
  export type InputTuple = [params: AaveLoopStrategyV3.RiskParamsStruct];
  export type OutputTuple = [params: AaveLoopStrategyV3.RiskParamsStructOutput];
  export interface OutputObject {
    params: AaveLoopStrategyV3.RiskParamsStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [caller: AddressLike, amount: BigNumberish];
  export type OutputTuple = [caller: string, amount: bigint];
  export interface OutputObject {
    caller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AaveLoopStrategyV3 extends BaseContract {
  connect(runner?: ContractRunner | null): AaveLoopStrategyV3;
  waitForDeployment(): Promise<this>;

  interface: AaveLoopStrategyV3Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LEVERAGE_PRECISION: TypedContractMethod<[], [bigint], "view">;

  aToken: TypedContractMethod<[], [string], "view">;

  aavePool: TypedContractMethod<[], [string], "view">;

  balanceOfPool: TypedContractMethod<[], [bigint], "view">;

  borrowAsset: TypedContractMethod<[], [string], "view">;

  currentLeverage: TypedContractMethod<[], [bigint], "view">;

  dataProvider: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  emergencyWithdraw: TypedContractMethod<
    [_to: AddressLike],
    [void],
    "nonpayable"
  >;

  estimatedAPY: TypedContractMethod<[], [bigint], "view">;

  estimatedTotalAssets: TypedContractMethod<[], [bigint], "view">;

  getAavePosition: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalCollateralBase: bigint;
        totalDebtBase: bigint;
        availableBorrowsBase: bigint;
        hf: bigint;
      }
    ],
    "view"
  >;

  getCurrentLeverage: TypedContractMethod<[], [bigint], "view">;

  harvest: TypedContractMethod<
    [],
    [[bigint, bigint] & { profit: bigint; loss: bigint }],
    "nonpayable"
  >;

  healthFactor: TypedContractMethod<[], [bigint], "view">;

  isActive: TypedContractMethod<[], [boolean], "view">;

  lastReportTime: TypedContractMethod<[], [bigint], "view">;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  rebalance: TypedContractMethod<[], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  riskParams: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        targetHealthFactor: bigint;
        minHealthFactor: bigint;
        maxLeverage: bigint;
        maxLoopIterations: bigint;
      }
    ],
    "view"
  >;

  setController: TypedContractMethod<
    [_controller: AddressLike],
    [void],
    "nonpayable"
  >;

  setRiskParams: TypedContractMethod<
    [_params: BytesLike],
    [void],
    "nonpayable"
  >;

  setRiskParamsDirect: TypedContractMethod<
    [
      _targetHealthFactor: BigNumberish,
      _minHealthFactor: BigNumberish,
      _maxLeverage: BigNumberish,
      _maxLoopIterations: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setVault: TypedContractMethod<[_vault: AddressLike], [void], "nonpayable">;

  strategyController: TypedContractMethod<[], [string], "view">;

  sweep: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  totalAssets: TypedContractMethod<[], [bigint], "view">;

  totalDebt: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  vault: TypedContractMethod<[], [string], "view">;

  want: TypedContractMethod<[], [string], "view">;

  wantToken: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LEVERAGE_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "aToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "aavePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOfPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "borrowAsset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentLeverage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dataProvider"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "estimatedAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "estimatedTotalAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAavePosition"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalCollateralBase: bigint;
        totalDebtBase: bigint;
        availableBorrowsBase: bigint;
        hf: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentLeverage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "harvest"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { profit: bigint; loss: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "healthFactor"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastReportTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "rebalance"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "riskParams"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        targetHealthFactor: bigint;
        minHealthFactor: bigint;
        maxLeverage: bigint;
        maxLoopIterations: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setController"
  ): TypedContractMethod<[_controller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRiskParams"
  ): TypedContractMethod<[_params: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRiskParamsDirect"
  ): TypedContractMethod<
    [
      _targetHealthFactor: BigNumberish,
      _minHealthFactor: BigNumberish,
      _maxLeverage: BigNumberish,
      _maxLoopIterations: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVault"
  ): TypedContractMethod<[_vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "strategyController"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sweep"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalDebt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "want"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "wantToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Harvested"
  ): TypedContractEvent<
    HarvestedEvent.InputTuple,
    HarvestedEvent.OutputTuple,
    HarvestedEvent.OutputObject
  >;
  getEvent(
    key: "LeverageDecreased"
  ): TypedContractEvent<
    LeverageDecreasedEvent.InputTuple,
    LeverageDecreasedEvent.OutputTuple,
    LeverageDecreasedEvent.OutputObject
  >;
  getEvent(
    key: "LeverageIncreased"
  ): TypedContractEvent<
    LeverageIncreasedEvent.InputTuple,
    LeverageIncreasedEvent.OutputTuple,
    LeverageIncreasedEvent.OutputObject
  >;
  getEvent(
    key: "LoopExecuted"
  ): TypedContractEvent<
    LoopExecutedEvent.InputTuple,
    LoopExecutedEvent.OutputTuple,
    LoopExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RiskParamsUpdated"
  ): TypedContractEvent<
    RiskParamsUpdatedEvent.InputTuple,
    RiskParamsUpdatedEvent.OutputTuple,
    RiskParamsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Harvested(uint256,uint256)": TypedContractEvent<
      HarvestedEvent.InputTuple,
      HarvestedEvent.OutputTuple,
      HarvestedEvent.OutputObject
    >;
    Harvested: TypedContractEvent<
      HarvestedEvent.InputTuple,
      HarvestedEvent.OutputTuple,
      HarvestedEvent.OutputObject
    >;

    "LeverageDecreased(uint256)": TypedContractEvent<
      LeverageDecreasedEvent.InputTuple,
      LeverageDecreasedEvent.OutputTuple,
      LeverageDecreasedEvent.OutputObject
    >;
    LeverageDecreased: TypedContractEvent<
      LeverageDecreasedEvent.InputTuple,
      LeverageDecreasedEvent.OutputTuple,
      LeverageDecreasedEvent.OutputObject
    >;

    "LeverageIncreased(uint256,uint256)": TypedContractEvent<
      LeverageIncreasedEvent.InputTuple,
      LeverageIncreasedEvent.OutputTuple,
      LeverageIncreasedEvent.OutputObject
    >;
    LeverageIncreased: TypedContractEvent<
      LeverageIncreasedEvent.InputTuple,
      LeverageIncreasedEvent.OutputTuple,
      LeverageIncreasedEvent.OutputObject
    >;

    "LoopExecuted(uint256,uint256,uint256)": TypedContractEvent<
      LoopExecutedEvent.InputTuple,
      LoopExecutedEvent.OutputTuple,
      LoopExecutedEvent.OutputObject
    >;
    LoopExecuted: TypedContractEvent<
      LoopExecutedEvent.InputTuple,
      LoopExecutedEvent.OutputTuple,
      LoopExecutedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RiskParamsUpdated(tuple)": TypedContractEvent<
      RiskParamsUpdatedEvent.InputTuple,
      RiskParamsUpdatedEvent.OutputTuple,
      RiskParamsUpdatedEvent.OutputObject
    >;
    RiskParamsUpdated: TypedContractEvent<
      RiskParamsUpdatedEvent.InputTuple,
      RiskParamsUpdatedEvent.OutputTuple,
      RiskParamsUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
