/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aaveV3StrategySol from "./AaveV3Strategy.sol";
export type { aaveV3StrategySol };
import type * as quickSwapV3StrategySol from "./QuickSwapV3Strategy.sol";
export type { quickSwapV3StrategySol };
export type { AaveStrategy } from "./AaveStrategy";
export type { QuickSwapStrategy } from "./QuickSwapStrategy";
export type { SimpleStrategy } from "./SimpleStrategy";
