/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFeeDistributorV3,
  IFeeDistributorV3Interface,
} from "../../../contracts/LocalStrategyManagerV3.sol/IFeeDistributorV3";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "distributeFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFeeDistributorV3__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeDistributorV3Interface {
    return new Interface(_abi) as IFeeDistributorV3Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFeeDistributorV3 {
    return new Contract(address, _abi, runner) as unknown as IFeeDistributorV3;
  }
}
